version: 0.1

phases:
  pre_build:
    commands:
      - echo "Installing Project Dependencies..."
      - npm install

  build:
    commands:
      - echo "Running lint..."
      - npm run lint

      - echo "Running tests..."
      - npm run test

      - echo "Packaging..."
      - npm run build

      - echo "Compiling Cloudformation (Bucket: $S3_BUCKET)..."
      - aws cloudformation package --template-file sam.yml --s3-bucket $S3_BUCKET --output-template-file template.yml

artifacts:
  discard-paths: yes
  files:
    template.yml
