AWSTemplateFormatVersion: "2010-09-09"

Description: "Creates a build, test and deployment pipeline"

Parameters:

  GitHubToken:
    Type: String
    NoEcho: true
    Description: A Github OAuth Token with public_repo or repo scope

  GitHubUser:
    Type: String
    Description: Organisation or Username that the repository belongs to

  Repo:
    Type: String
    Description: The name of the repository

  Branch:
    Type: String
    Default: master
    Description: Branch to use from the repository.

  TemplateFileName:
    Type: String
    Default: template.yml
    Description: Name of the Build output template file

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "GitHub Configuration"
        Parameters:
          - GitHubToken
          - GitHubUser
      - Label:
          default: "Repository Configuration"
        Parameters:
          - Repo
          - Branch
      - Label:
          default: "Build Configuration"
        Parameters:
          - TemplateFileName
    ParameterLabels:
      GitHubToken:
        default: "GitHub Personal Access Token"
      GitHubUser:
        default: "Username or Organisation Name"
      Repo:
        default: "Repository Name"
      Branch:
        default: "Branch on Repository"
      TemplateFileName:
        default: "Cloudformation Template Name"

Resources:

  PipelineArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  PipelineSNSTopic:
    Type: AWS::SNS::Topic

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RestartExecutionOnUpdate: false
      ArtifactStore:
        Location:
          Ref: PipelineArtifactStore
        Type: S3
      RoleArn:
        Fn::GetAtt: [PipelineRole, Arn]
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref GitHubToken
        - Name: Build
          Actions:
            - Name: Build
              RunOrder: 2
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                Name:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}"
                ServiceRole:
                  Fn::GetAtt: [BuildRole, Arn]
                Environment:
                  Type: LINUX_CONTAINER
                  ComputeType: BUILD_GENERAL1_SMALL
                  Image: aws/codebuild/nodejs:6.3.1
                  EnvironmentVariables:
                  - Name: S3_BUCKET
                    Value:
                      Ref: PipelineArtifactStore
                  - Name: TEMPLATE_FILE_NAME
                    Value:
                      Ref: TemplateFileName
                TimeoutInMinutes: 10
        - Name: Test
          Actions:
            - Name: CreateStack
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn:
                  Fn::GetAtt: [CloudformationRole, Arn]
                StackName:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}-test"
                TemplatePath:
                  Fn::Sub: "TemplateSource::${TemplateFileName}"
            - Name: ApproveTestStack
              RunOrder: 2
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                NotificationArn:
                  Ref: PipelineSNSTopic
                CustomData:
                  Fn::Sub: 'Do you want to create a change set against the production stack and delete the ${GitHubUser}-${Repo}-${Branch}-test stack?'
            - Name: DeleteTestStack
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: DELETE_ONLY
                RoleArn:
                  Fn::GetAtt: [CloudformationRole, Arn]
                StackName:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}-test"
        - Name: Release
          Actions:
            - Name: CreateChangeSet
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn:
                  Fn::GetAtt: [CloudformationRole, Arn]
                StackName:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}"
                ChangeSetName:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}-changeset"
                TemplatePath:
                  Fn::Sub: "TemplateSource::${TemplateFileName}"
            - Name: ApproveChangeSet
              RunOrder: 2
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                NotificationArn:
                  Ref: PipelineSNSTopic
                CustomData:
                  Fn::Sub: 'A new change set was created for the ${GitHubUser}-${Repo}-${Branch} stack. Do you want to implement the changes?'
            - Name: ExecuteChangeSet
              RunOrder: 3
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}-changeset"
                RoleArn:
                  Fn::GetAtt: [CloudformationRole, Arn]
                StackName:
                  Fn::Sub: "${GitHubUser}-${Repo}-${Branch}"

  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'lambda:*'
                  - 'dynamodb:*'
                  - 'sns:*'
                Effect: Allow
                Resource: '*'

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 's3:*'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:SetStackPolicy'
                  - 'iam:PassRole'
                  - 'sns:Publish'
                Effect: Allow
                Resource: '*'

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildPackageAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 's3:*'
                  - 'cloudformation:*'
                Effect: Allow
                Resource: '*'
